package kayleh.wizard.community.mapper;

import kayleh.wizard.community.dto.QuestionQueryDTO;
import kayleh.wizard.community.model.Question;

import java.util.List;

public interface QuestionExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sun May 24 21:29:32 CST 2020
     */
    int inView(Question record);
    int inCommentCount(Question record);
    List<Question> selectRelated(Question question);

    Integer countBySearch(QuestionQueryDTO questionQueryDTO);

    List<Question> selectBySearch(QuestionQueryDTO questionQueryDTO);

//    List<Question> selectZero(QuestionQueryDTO questionQueryDTO);
}